### PR TITLE
Add srmourasilva-plugins: Gossiper, Tetr4-switch

### PR DESCRIPTION
**Pull request by SrMouraSilva**
Add plugins Gossiper and Tetr4-switch.

You can see details about them into:
* Gossiper: https://forum.mod.audio/t/gossiper-plugin-to-say-what-is-happening-when-you-are-looking-it/9660
* Tetr4-switch: https://forum.mod.audio/t/tetr4-switch-plugin-in-development/8998

### CODE REVIEW

**Comment by falkTX** [comment]
Hi, I would love to come back to this and your plugins.
Previously I told you it was best to wait until the juce situation was sorted on MOD side, which is done now, but checking your plugin code I see you do not use juce at all.

So the line in your mk file here is not needed and actually confusing:
```
PEDAL_PI_PLUGINS_CONF_OPTS = -DCMAKE_TOOLCHAIN_FILE=$(JUCE6_TOOLCHAIN_FILE) -DSKIP_LV2_TTL_GENERATOR=ON
```

What is the state of the plugins? any outstanding bugs?

For the gossiper plugin, I still maintain the stance that plugins cannot/wont show HMI popups unless they have something addressed to the HMI first.
If that is something you are ok with, we can proceed with that plugin too.

Also, the gossiper plugin only makes sense on units with HMI widgets, correct? So if pushing to the store we skip Duo units as it does not have the feature.

**Comment by SrMouraSilva** [comment]
> What is the state of the plugins? any outstanding bugs?

I consider that Tetr4Switch is fine.

Related to Gossiper, I noticed that sometimes, the first popup don't show. I am not sure if is something related to my code (which is the most probable) or something related to the Midi device.

Also related to Gossiper, I create some text parameters for customizing popup text. 
https://github.com/SrMouraSilva/plugins-lv2/blob/master/plugins/resources/gossiper.lv2/gossiper.ttl#L393-L421
But I didn't finished because I don't know how to do it. I you have any tip, like a sample code, I will appreciate so much!

> For the gossiper plugin, I still maintain the stance that plugins cannot/wont show HMI popups unless they have something addressed to the HMI first.
If that is something you are ok with, we can proceed with that plugin too.

I am ok with it.

> Also, the gossiper plugin only makes sense on units with HMI widgets, correct? So if pushing to the store we skip Duo units as it does not have the feature.

Yes, I suppose that it will not be useful for this devices.

**Comment by SrMouraSilva** [comment]
> So the line in your mk file here is not needed and actually confusing:
> ```
PEDAL_PI_PLUGINS_CONF_OPTS = -DCMAKE_TOOLCHAIN_FILE=$(JUCE6_TOOLCHAIN_FILE) -DSKIP_LV2_TTL_GENERATOR=ON
```

I update the PR

**Comment by falkTX** [comment]
Lets get back to this. I want to merge and push these plugins to the beta store, they are interesting and useful.
Sorry for the long delay!

But I see a bit of an issue.. the plugin collection name is too generic, there are other projects out there called pedal-pi.
So I need to ask for a rename, to make them more recognizable.
I really dont mind the name but "pedal pi" is something I have read about online and it is often not related to these plugins.

**Comment by SrMouraSilva** [comment]
Hello, @falkTX. I choose Pedal pi because I have a project with this name. When I created this name, at the same time other projects were created with the same name.

I can change to srmourasilva. Do you have other suggestions?

**Comment by falkTX** [comment]
> Hello, @falkTX. I choose Pedal pi because I have a project with this name. When I created this name, at the same time other projects were created with the same name.
> 
> I can change to srmourasilva. Do you have other suggestions?

so srmourasilva-plugins :D that works

you can remove the PEDAL_PI_PLUGINS_DEPENDENCIES line since it is empty. otherwise all fine.
the bundle names can remain the same as to keep compatibility with the users that already tried it before.

I didnt actually try the plugins yet myself, this was more of a casual checkup before pushing them to beta.

**Comment by SrMouraSilva** [comment]
Hello, @falkTX. Good day

I updated as requested. Let me know if there is something more missing :)

**Comment by falkTX** [comment]
its all good, let me push these to beta now. will let you know if the build fails

**Comment by SrMouraSilva** [comment]
Thank you falkTX

**Comment by falkTX** [comment]
would tetr4-switch be useful without HMI? was wondering about adding it to mod-desktop, but can only work if the hmi widgets use becomes optional

**Pull request merged**
